//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GateEntryChild_Mid_History
    {
        public int Id { get; set; }
        public Nullable<decimal> UId { get; set; }
        public Nullable<decimal> MUId { get; set; }
        public string GateEntryNo { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> StatusTypeId { get; set; }
        public string StatusTypeNo { get; set; }
        public Nullable<decimal> StatusChildId { get; set; }
        public Nullable<decimal> ReceiveQty { get; set; }
        public string ItemNo { get; set; }
        public string Item { get; set; }
        public string ItemGroup { get; set; }
        public string ItemGroupNo { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Vendor { get; set; }
        public string VendorNo { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string InOut { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Unit { get; set; }
        public string UnitNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModyfiedBy { get; set; }
        public Nullable<System.DateTime> ModyfiedDate { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<decimal> TaxPer { get; set; }
        public Nullable<decimal> DeliveryUnitCharge { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> DeliveryAmount { get; set; }
        public Nullable<decimal> AllAmount { get; set; }
        public Nullable<System.DateTime> GateEntryDate { get; set; }
        public Nullable<decimal> MRN_Receive { get; set; }
    }
}
