//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GateEntry_Mid_history
    {
        public int Id { get; set; }
        public Nullable<decimal> UId { get; set; }
        public Nullable<int> GateEntryId { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> SessionId { get; set; }
        public string GateEntryNo { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> StatusTypeId { get; set; }
        public string StatusTypeNo { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public string CreatedBy { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string IsMRN_Number { get; set; }
    }
}
