//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MMSEntities : DbContext
    {
        public MMSEntities()
            : base("name=MMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlockMaster> BlockMasters { get; set; }
        public virtual DbSet<FloorMaster> FloorMasters { get; set; }
        public virtual DbSet<GateEntry> GateEntries { get; set; }
        public virtual DbSet<GateEntry_Mid> GateEntry_Mid { get; set; }
        public virtual DbSet<GateEntry_Mid_history> GateEntry_Mid_history { get; set; }
        public virtual DbSet<GateEntryChild> GateEntryChilds { get; set; }
        public virtual DbSet<GateEntryChild_Mid> GateEntryChild_Mid { get; set; }
        public virtual DbSet<GateEntryChild_Mid_History> GateEntryChild_Mid_History { get; set; }
        public virtual DbSet<ns_AddPriceCap> ns_AddPriceCap { get; set; }
        public virtual DbSet<ns_Price_Cap_Enable_Item_Group> ns_Price_Cap_Enable_Item_Group { get; set; }
        public virtual DbSet<ns_RateNotification> ns_RateNotification { get; set; }
        public virtual DbSet<ns_tbl_ApprovedItemQuantity> ns_tbl_ApprovedItemQuantity { get; set; }
        public virtual DbSet<ns_tbl_IssueQuantity> ns_tbl_IssueQuantity { get; set; }
        public virtual DbSet<nstblStockDEMO> nstblStockDEMOes { get; set; }
        public virtual DbSet<PurchaseRequisitionChild> PurchaseRequisitionChilds { get; set; }
        public virtual DbSet<PurchaseRequisitionMaster> PurchaseRequisitionMasters { get; set; }
        public virtual DbSet<SessionMaster> SessionMasters { get; set; }
        public virtual DbSet<TbCashPurchaseChild> TbCashPurchaseChilds { get; set; }
        public virtual DbSet<TbCashPurchaseMaster> TbCashPurchaseMasters { get; set; }
        public virtual DbSet<TbDelivery_Details_PO_History> TbDelivery_Details_PO_History { get; set; }
        public virtual DbSet<TbIndentPurchaseOrder_Approval_For_Print> TbIndentPurchaseOrder_Approval_For_Print { get; set; }
        public virtual DbSet<TbIndentPurchaseOrder_GST> TbIndentPurchaseOrder_GST { get; set; }
        public virtual DbSet<TbIndentPurchaseOrder_GST_History> TbIndentPurchaseOrder_GST_History { get; set; }
        public virtual DbSet<TbIndentPurchaseOrderChild> TbIndentPurchaseOrderChilds { get; set; }
        public virtual DbSet<TbIndentPurchaseOrderChild_GST> TbIndentPurchaseOrderChild_GST { get; set; }
        public virtual DbSet<TbIndentPurchaseOrderChild_GST_History> TbIndentPurchaseOrderChild_GST_History { get; set; }
        public virtual DbSet<TbIndentPurchaseOrderMaster> TbIndentPurchaseOrderMasters { get; set; }
        public virtual DbSet<tbl_beforPIdecesionPurchase> tbl_beforPIdecesionPurchase { get; set; }
        public virtual DbSet<tbl_PurchaseOrderAttachFiles> tbl_PurchaseOrderAttachFiles { get; set; }
        public virtual DbSet<tbl_PurchaseRequistionAttachFiles> tbl_PurchaseRequistionAttachFiles { get; set; }
        public virtual DbSet<tbl_wmntdata> tbl_wmntdata { get; set; }
        public virtual DbSet<tblAccountType> tblAccountTypes { get; set; }
        public virtual DbSet<tblALLRemark> tblALLRemarks { get; set; }
        public virtual DbSet<tblApproval_AccountType> tblApproval_AccountType { get; set; }
        public virtual DbSet<tblApprovalStatu> tblApprovalStatus { get; set; }
        public virtual DbSet<tblBillingAddress> tblBillingAddresses { get; set; }
        public virtual DbSet<tblClosedPurchaseOrder> tblClosedPurchaseOrders { get; set; }
        public virtual DbSet<tblDepartment> tblDepartments { get; set; }
        public virtual DbSet<tblDesignation> tblDesignations { get; set; }
        public virtual DbSet<tblDivisionMaster> tblDivisionMasters { get; set; }
        public virtual DbSet<tblEmployeeMaster> tblEmployeeMasters { get; set; }
        public virtual DbSet<tblEquipmentCategory> tblEquipmentCategories { get; set; }
        public virtual DbSet<tblEquipmentSubCategory> tblEquipmentSubCategories { get; set; }
        public virtual DbSet<tblFinancialSelectionType> tblFinancialSelectionTypes { get; set; }
        public virtual DbSet<tblGenral_Terms_Conditions> tblGenral_Terms_Conditions { get; set; }
        public virtual DbSet<tblGenral_Terms_Conditions_Child> tblGenral_Terms_Conditions_Child { get; set; }
        public virtual DbSet<tblGenral_Terms_Conditions_Child_History> tblGenral_Terms_Conditions_Child_History { get; set; }
        public virtual DbSet<tblGetOutTransfer> tblGetOutTransfers { get; set; }
        public virtual DbSet<tblGST_SplitTaxMaster> tblGST_SplitTaxMaster { get; set; }
        public virtual DbSet<tblIndentRequisition> tblIndentRequisitions { get; set; }
        public virtual DbSet<tblInterStateTransferChild> tblInterStateTransferChilds { get; set; }
        public virtual DbSet<tblInterStateTransferMaster> tblInterStateTransferMasters { get; set; }
        public virtual DbSet<tblIntraStateTransferChild> tblIntraStateTransferChilds { get; set; }
        public virtual DbSet<tblIntraStateTransferMaster> tblIntraStateTransferMasters { get; set; }
        public virtual DbSet<tblIntraStateTransferTaxableChild> tblIntraStateTransferTaxableChilds { get; set; }
        public virtual DbSet<tblItemBudget> tblItemBudgets { get; set; }
        public virtual DbSet<tblItemCurrentStock> tblItemCurrentStocks { get; set; }
        public virtual DbSet<tblItemExcessPercentageHistory> tblItemExcessPercentageHistories { get; set; }
        public virtual DbSet<tblItemGroupMaster> tblItemGroupMasters { get; set; }
        public virtual DbSet<tblItemMaster> tblItemMasters { get; set; }
        public virtual DbSet<tblItemMasterFirstOpening> tblItemMasterFirstOpenings { get; set; }
        public virtual DbSet<tblItemMasterStock> tblItemMasterStocks { get; set; }
        public virtual DbSet<tblItemOpeningDeletedHistory> tblItemOpeningDeletedHistories { get; set; }
        public virtual DbSet<tblLogInformation> tblLogInformations { get; set; }
        public virtual DbSet<tblMachineMaster> tblMachineMasters { get; set; }
        public virtual DbSet<tblMainHeader> tblMainHeaders { get; set; }
        public virtual DbSet<tblMakeMaster> tblMakeMasters { get; set; }
        public virtual DbSet<tblMang_PI_Approval_History> tblMang_PI_Approval_History { get; set; }
        public virtual DbSet<tblMMSCartageType> tblMMSCartageTypes { get; set; }
        public virtual DbSet<tblMMSEquipmentMaster> tblMMSEquipmentMasters { get; set; }
        public virtual DbSet<tblMMSExciseDuty> tblMMSExciseDuties { get; set; }
        public virtual DbSet<tblMMSGateEntryFileDirectory> tblMMSGateEntryFileDirectories { get; set; }
        public virtual DbSet<tblMMSGSTTaxType> tblMMSGSTTaxTypes { get; set; }
        public virtual DbSet<tblMMSInsuranceMaster> tblMMSInsuranceMasters { get; set; }
        public virtual DbSet<tblMMSMRNEntryFileDirectory> tblMMSMRNEntryFileDirectories { get; set; }
        public virtual DbSet<tblMMSPCDebitNote> tblMMSPCDebitNotes { get; set; }
        public virtual DbSet<tblMMSQuotation> tblMMSQuotations { get; set; }
        public virtual DbSet<tblMMSQuotation_Document> tblMMSQuotation_Document { get; set; }
        public virtual DbSet<tblMMSTaxValue> tblMMSTaxValues { get; set; }
        public virtual DbSet<tblMMSUserPermission> tblMMSUserPermissions { get; set; }
        public virtual DbSet<tblMovableStatusMaster> tblMovableStatusMasters { get; set; }
        public virtual DbSet<tblMovingDescription> tblMovingDescriptions { get; set; }
        public virtual DbSet<tblOutProApprovalLimit> tblOutProApprovalLimits { get; set; }
        public virtual DbSet<tblPC_RegistrationType> tblPC_RegistrationType { get; set; }
        public virtual DbSet<tblPI_PurchaseType> tblPI_PurchaseType { get; set; }
        public virtual DbSet<tblPIC_PI_Approval_History> tblPIC_PI_Approval_History { get; set; }
        public virtual DbSet<tblPIPurchasedecisionType> tblPIPurchasedecisionTypes { get; set; }
        public virtual DbSet<tblProjectCode> tblProjectCodes { get; set; }
        public virtual DbSet<tblProjectGSTNo> tblProjectGSTNoes { get; set; }
        public virtual DbSet<tblProjectMaster> tblProjectMasters { get; set; }
        public virtual DbSet<tblProjectOpeningAndClosingDate> tblProjectOpeningAndClosingDates { get; set; }
        public virtual DbSet<tblProjectParticularsDetailA> tblProjectParticularsDetailAs { get; set; }
        public virtual DbSet<tblProjectTINNo> tblProjectTINNoes { get; set; }
        public virtual DbSet<tblPurchaseLimitValueByProjectWise> tblPurchaseLimitValueByProjectWises { get; set; }
        public virtual DbSet<tblPurchaseOrderApprovalLimitValue> tblPurchaseOrderApprovalLimitValues { get; set; }
        public virtual DbSet<tblPurchaseRequisitionApprovalLimitValue> tblPurchaseRequisitionApprovalLimitValues { get; set; }
        public virtual DbSet<tblReasonCloserMaster> tblReasonCloserMasters { get; set; }
        public virtual DbSet<tblReceiveData> tblReceiveDatas { get; set; }
        public virtual DbSet<tblRegion> tblRegions { get; set; }
        public virtual DbSet<tblRegistrationType> tblRegistrationTypes { get; set; }
        public virtual DbSet<tblReturnQtyChild> tblReturnQtyChilds { get; set; }
        public virtual DbSet<tblReturnQtyMaster> tblReturnQtyMasters { get; set; }
        public virtual DbSet<tblReturnReasonMaster> tblReturnReasonMasters { get; set; }
        public virtual DbSet<tblRolemaster> tblRolemasters { get; set; }
        public virtual DbSet<tblSourceLocation> tblSourceLocations { get; set; }
        public virtual DbSet<tblSpecific_Instructions> tblSpecific_Instructions { get; set; }
        public virtual DbSet<tblSpecific_Instructions_Child> tblSpecific_Instructions_Child { get; set; }
        public virtual DbSet<tblSpecific_Instructions_Child_History> tblSpecific_Instructions_Child_History { get; set; }
        public virtual DbSet<tblSpecificTermsAndCondition> tblSpecificTermsAndConditions { get; set; }
        public virtual DbSet<tblSpecificTermsAndConditions_Child> tblSpecificTermsAndConditions_Child { get; set; }
        public virtual DbSet<tblSpecificTermsAndConditions_Child_History> tblSpecificTermsAndConditions_Child_History { get; set; }
        public virtual DbSet<tblSubHeader> tblSubHeaders { get; set; }
        public virtual DbSet<tblTaxPayableOnReverseCharge> tblTaxPayableOnReverseCharges { get; set; }
        public virtual DbSet<tblTransfertypeselection> tblTransfertypeselections { get; set; }
        public virtual DbSet<tblTransportationModeNew> tblTransportationModeNews { get; set; }
        public virtual DbSet<tblUnitConversionMaster> tblUnitConversionMasters { get; set; }
        public virtual DbSet<tblUniteConversionMapped> tblUniteConversionMappeds { get; set; }
        public virtual DbSet<tblUnitMaster> tblUnitMasters { get; set; }
        public virtual DbSet<tblUploadedBill> tblUploadedBills { get; set; }
        public virtual DbSet<tblUserDivision> tblUserDivisions { get; set; }
        public virtual DbSet<tblVehicleType> tblVehicleTypes { get; set; }
        public virtual DbSet<tblVendorDebitNoteChild> tblVendorDebitNoteChilds { get; set; }
        public virtual DbSet<tblVendorDebitNoteMaster> tblVendorDebitNoteMasters { get; set; }
        public virtual DbSet<tblVendorMaster> tblVendorMasters { get; set; }
        public virtual DbSet<tblVendorTypeMaster> tblVendorTypeMasters { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<tblCityList_old> tblCityList_old { get; set; }
        public virtual DbSet<tblCountry> tblCountries { get; set; }
        public virtual DbSet<tblState> tblStates { get; set; }
        public virtual DbSet<tblIntraTransferTaxableMaster> tblIntraTransferTaxableMasters { get; set; }
        public virtual DbSet<tblCityList> tblCityLists { get; set; }
        public virtual DbSet<tblPcContractorMaster> tblPcContractorMasters { get; set; }
        public virtual DbSet<tbl_ContactPersonMaster> tbl_ContactPersonMaster { get; set; }
        public virtual DbSet<TbDelivery_Details_PO> TbDelivery_Details_PO { get; set; }
        public virtual DbSet<tbl_OfficeAddress> tbl_OfficeAddress { get; set; }
        public virtual DbSet<tbl_TCSTaxMaster> tbl_TCSTaxMaster { get; set; }
        public virtual DbSet<TbDraftDelivery_Details_PO> TbDraftDelivery_Details_PO { get; set; }
        public virtual DbSet<TbDraftIndentPurchaseOrder_GST> TbDraftIndentPurchaseOrder_GST { get; set; }
        public virtual DbSet<TbDraftIndentPurchaseOrderChild_GST> TbDraftIndentPurchaseOrderChild_GST { get; set; }
        public virtual DbSet<tbl_ProjectMonthBudget> tbl_ProjectMonthBudget { get; set; }
        public virtual DbSet<tbl_ProjectYearBudget> tbl_ProjectYearBudget { get; set; }
        public virtual DbSet<tblDraftGenral_Terms_Conditions_Child> tblDraftGenral_Terms_Conditions_Child { get; set; }
        public virtual DbSet<tblDraftSpecific_Instructions_Child> tblDraftSpecific_Instructions_Child { get; set; }
        public virtual DbSet<tblDraftSpecificTermsAndConditions_Child> tblDraftSpecificTermsAndConditions_Child { get; set; }
    }
}
