//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ns_tbl_ApprovedItemQuantity
    {
        public int Id { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string IndentNo { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string ItemGroupID { get; set; }
        public string ItemGroupName { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string UnitID { get; set; }
        public string Make { get; set; }
        public string PartNo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ApprovedQuantity { get; set; }
        public string SessionId { get; set; }
        public string SiteId { get; set; }
        public string ApproveddBy { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
