//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequisitionChild
    {
        public decimal UId { get; set; }
        public Nullable<decimal> MId { get; set; }
        public string PurRequisitionNo { get; set; }
        public Nullable<int> SNo { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public string ItemNo { get; set; }
        public string ItemName { get; set; }
        public string UnitNo { get; set; }
        public string Unit { get; set; }
        public string ItemGroupNo { get; set; }
        public string ItemGroupName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SessionId { get; set; }
        public Nullable<decimal> DemandQty { get; set; }
        public Nullable<decimal> ApprovedQty { get; set; }
        public Nullable<decimal> OrderedQty { get; set; }
        public Nullable<decimal> LastPurchaseRate { get; set; }
        public Nullable<decimal> CurrentRate { get; set; }
        public Nullable<decimal> CurrentValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> ApprovedQtyPIC { get; set; }
        public string PICStatus { get; set; }
        public string MangStatus { get; set; }
        public Nullable<decimal> ApprovedQtyMang { get; set; }
        public Nullable<decimal> PICCurrentValue { get; set; }
        public Nullable<decimal> MangCurrentValue { get; set; }
        public Nullable<decimal> ReceiveUpto { get; set; }
        public Nullable<decimal> Balanced { get; set; }
    }
}
