//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRequisitionMaster
    {
        public decimal UId { get; set; }
        public Nullable<int> Id { get; set; }
        public string PurRequisitionNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string SendTo { get; set; }
        public string SendToName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SessionId { get; set; }
        public string Comp { get; set; }
        public string CompO { get; set; }
        public string AllItemPICStatus { get; set; }
        public string AllItemMangStatus { get; set; }
        public Nullable<bool> CheckedBeyondPIC_Limit { get; set; }
        public Nullable<int> PurchasePI_Type { get; set; }
        public string ForwardToMang { get; set; }
        public string Remarks { get; set; }
        public string PICRemarks { get; set; }
        public string MangRemarks { get; set; }
        public Nullable<int> PurchasePIC_Type { get; set; }
        public string PurchasePICChangedBy { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> PurchaseMang_Type { get; set; }
        public Nullable<System.DateTime> RemarksDate { get; set; }
        public Nullable<System.DateTime> PICDate { get; set; }
        public Nullable<System.DateTime> MangDate { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> Is_Dis { get; set; }
        public string Dis_Remark { get; set; }
        public string Dis_By { get; set; }
        public Nullable<System.DateTime> Dis_Date { get; set; }
    }
}
