//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbCashPurchaseMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbCashPurchaseMaster()
        {
            this.TbCashPurchaseChilds = new HashSet<TbCashPurchaseChild>();
        }
    
        public decimal UId { get; set; }
        public Nullable<int> CashPurchaseId { get; set; }
        public string CashPurchaseNo { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string VendorId { get; set; }
        public string VendorName { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string Delivery_Address { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public Nullable<decimal> P_F { get; set; }
        public Nullable<decimal> ExciseDuty { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> D_Charges { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> RondOff { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string EmpId { get; set; }
        public string EmpName { get; set; }
        public string CreatedBy { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Complete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbCashPurchaseChild> TbCashPurchaseChilds { get; set; }
        public virtual tblVendorMaster tblVendorMaster { get; set; }
    }
}
