//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDelivery_Details_PO
    {
        public int Id { get; set; }
        public string ProjectId { get; set; }
        public string Purchase_order_No { get; set; }
        public string Delivery_Schedule { get; set; }
        public string Delivery_Address { get; set; }
        public string Billing_Address { get; set; }
        public string Contact_Person_Name { get; set; }
        public string Contact_Person_Mobile { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string EditStatus { get; set; }
        public string CompanyId { get; set; }
        public string Status { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string StoreKeeperName { get; set; }
        public string StoreKeeperContact { get; set; }
        public string EPContactPerID { get; set; }
        public Nullable<int> ContactDivType { get; set; }
    }
}
