//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbIndentPurchaseOrder_Approval_For_Print
    {
        public int Id { get; set; }
        public string ProjectId { get; set; }
        public string Purchase_Order_Indent_No { get; set; }
        public string Created_Employee_Id { get; set; }
        public string PurchaseRefNo { get; set; }
        public string Vendor_Group_Id { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string Project_Name { get; set; }
        public string Employee_Name { get; set; }
        public string Vendor_Name { get; set; }
        public string Updated_Employee_Id { get; set; }
        public string Send_To { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Status_Approval { get; set; }
        public string ForwordTo { get; set; }
        public string EditedStatus { get; set; }
        public Nullable<bool> IsPORelease { get; set; }
        public string POReleaseBy { get; set; }
        public Nullable<System.DateTime> POReleaseDate { get; set; }
        public string FirstLevelApprv_Id { get; set; }
        public string FirstLevelApprv_Remarks { get; set; }
        public string FirstLevelApprv_Status { get; set; }
        public Nullable<System.DateTime> FirstLevelApprv_Date { get; set; }
        public string SecondLevelApprv_Id { get; set; }
        public string SecondLevelApprv_Remarks { get; set; }
        public string SecondLevelApprv_Status { get; set; }
        public Nullable<System.DateTime> SecondLevelApprv_Date { get; set; }
    }
}
