//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbIndentPurchaseOrderMaster
    {
        public decimal UId { get; set; }
        public string ProjectNo { get; set; }
        public string SupplierNo { get; set; }
        public string PurchaseOrderNo { get; set; }
        public Nullable<int> PurchaseOrderId { get; set; }
        public Nullable<System.DateTime> PurchaseOrderDate { get; set; }
        public Nullable<int> SessionId { get; set; }
        public string IndentRefNo { get; set; }
        public string AcilTinNo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> SurCharge { get; set; }
        public Nullable<decimal> Cartage { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string Rupees { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SendTo { get; set; }
        public string Complete { get; set; }
        public string Status { get; set; }
        public string Forword_To { get; set; }
        public string SendFrom { get; set; }
        public string Reference { get; set; }
        public string Vendor_Group_Id { get; set; }
        public string Edited_Status { get; set; }
        public Nullable<decimal> Cartage_Rate { get; set; }
        public string Cartage_Type { get; set; }
        public Nullable<decimal> ExciseDutyRate { get; set; }
        public Nullable<decimal> ExciseDuty { get; set; }
        public string QuotationRefNo { get; set; }
        public Nullable<decimal> SubTotal2 { get; set; }
        public Nullable<bool> CheckedBeyondPOLimit { get; set; }
        public string Purchase_Id { get; set; }
        public string PMC_Id { get; set; }
        public string Purchase_Status { get; set; }
        public string PMC_Status { get; set; }
        public string Purchase_Remarks { get; set; }
        public string PMC_Remarks { get; set; }
        public Nullable<bool> IsPORelease { get; set; }
        public string POReleaseBy { get; set; }
        public Nullable<System.DateTime> POReleaseDate { get; set; }
        public string Remarks { get; set; }
        public string POType { get; set; }
    }
}
