//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OfficeAddress
    {
        public int UId { get; set; }
        public Nullable<int> Division { get; set; }
        public string OfficeName { get; set; }
        public string OfficeAddress { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Pin { get; set; }
        public string ContactNumber { get; set; }
        public string ContactPerson { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Mobile { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    }
}
