//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProjectYearBudget
    {
        public int UID { get; set; }
        public string ProjectID { get; set; }
        public string BudgetYear { get; set; }
        public string ItemID { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public Nullable<decimal> ItemRate { get; set; }
        public Nullable<decimal> TotalAmt { get; set; }
        public Nullable<decimal> TotalRecQty { get; set; }
        public Nullable<decimal> TotalRecAmt { get; set; }
        public string Remark { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyOn { get; set; }
    }
}
