//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ContactPersonMaster
    {
        public int UID { get; set; }
        public string Divison { get; set; }
        public string PersonName { get; set; }
        public string Designation { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedData { get; set; }
        public string ContactPersonCode { get; set; }
    }
}
