//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_wmntdata
    {
        public int Id { get; set; }
        public Nullable<int> txn_no { get; set; }
        public string wtype { get; set; }
        public Nullable<decimal> weight1 { get; set; }
        public string mchar1 { get; set; }
        public string date1 { get; set; }
        public string time1 { get; set; }
        public Nullable<decimal> weight2 { get; set; }
        public string mchar2 { get; set; }
        public string date2 { get; set; }
        public string time2 { get; set; }
        public Nullable<decimal> charge1 { get; set; }
        public Nullable<decimal> charge2 { get; set; }
        public string entry1 { get; set; }
        public string entry2 { get; set; }
        public string entry3 { get; set; }
        public string entry4 { get; set; }
        public string entry5 { get; set; }
        public string entry6 { get; set; }
        public string entry7 { get; set; }
        public string entry8 { get; set; }
        public string entry9 { get; set; }
        public string entry10 { get; set; }
        public string username { get; set; }
        public string username2 { get; set; }
        public Nullable<int> syn { get; set; }
    }
}
