//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCityList
    {
        public string CityID { get; set; }
        public string StateID { get; set; }
        public string CityName { get; set; }
        public Nullable<bool> ctStatus { get; set; }
    }
}
