//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDraftGenral_Terms_Conditions_Child
    {
        public int Id { get; set; }
        public string Header_Title { get; set; }
        public string GTC_Description { get; set; }
        public string Purchase_Order_No { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Edited_Status { get; set; }
        public string Status { get; set; }
        public string IsActive { get; set; }
        public string ProjectId { get; set; }
        public Nullable<int> GTC_Master_ID { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
