//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeMaster
    {
        public int TransID { get; set; }
        public string CompanyID { get; set; }
        public string ProjectID { get; set; }
        public string EmpID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string AccountType { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string AltEmail { get; set; }
        public string ReportingTo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public string DeptID { get; set; }
        public string DesgID { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string OfficialEmpID { get; set; }
        public string EmpType { get; set; }
        public string PurchaseType { get; set; }
        public Nullable<int> RoleId { get; set; }
    }
}
