//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGST_SplitTaxMaster
    {
        public int TransId { get; set; }
        public string TaxSlabCode { get; set; }
        public string TaxSlab { get; set; }
        public Nullable<decimal> TaxSlabPercentage { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> UGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public string TaxCode { get; set; }
        public string TaxRateType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
