//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGetOutTransfer
    {
        public int TransId { get; set; }
        public string GetOutNumber { get; set; }
        public string ProjectId { get; set; }
        public string TransferProjectId { get; set; }
        public string TransferNumber { get; set; }
        public string ItemGroupId { get; set; }
        public string ItemId { get; set; }
        public string UnitId { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public Nullable<decimal> DeliveryQty { get; set; }
        public Nullable<decimal> GetOutQty { get; set; }
        public Nullable<decimal> AvalStockAfterGetOut { get; set; }
        public Nullable<System.DateTime> GetOutDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TransferType { get; set; }
        public Nullable<decimal> TransferChildId { get; set; }
        public string ChalanNo { get; set; }
        public Nullable<System.DateTime> ChalanDate { get; set; }
        public string VehicleNo { get; set; }
        public string Session_Year { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string EwayBillNo { get; set; }
    }
}
