//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemOpeningDeletedHistory
    {
        public int TransID { get; set; }
        public string ItemId { get; set; }
        public string ItemGroupId { get; set; }
        public string ItemUnitId { get; set; }
        public string ProjectId { get; set; }
        public Nullable<decimal> Item_ReceiveQty { get; set; }
        public Nullable<decimal> Item_IssueQty { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
