//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblItemMaster()
        {
            this.TbCashPurchaseChilds = new HashSet<TbCashPurchaseChild>();
        }
    
        public int TransID { get; set; }
        public string CompanyID { get; set; }
        public string ItemID { get; set; }
        public string ItemGroupID { get; set; }
        public string ItemName { get; set; }
        public string UnitID { get; set; }
        public string Make { get; set; }
        public string PartNo { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string IssuingUnitID { get; set; }
        public Nullable<decimal> ConversionRatio { get; set; }
        public string Returnable { get; set; }
        public string ItemDescription { get; set; }
        public string HSNCode { get; set; }
        public string GITEMCode { get; set; }
        public Nullable<decimal> Excess_Item_Percentage { get; set; }
        public string Disable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbCashPurchaseChild> TbCashPurchaseChilds { get; set; }
        public virtual tblItemGroupMaster tblItemGroupMaster { get; set; }
        public virtual tblUnitMaster tblUnitMaster { get; set; }
        public virtual tblUnitMaster tblUnitMaster1 { get; set; }
    }
}
