//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInterStateTransferMaster
    {
        public decimal TransId { get; set; }
        public string InterTransferNumber { get; set; }
        public string ProjectId { get; set; }
        public string TransferProjectId { get; set; }
        public Nullable<int> ModeofTPT { get; set; }
        public Nullable<int> VehicleType { get; set; }
        public string VehicleNo { get; set; }
        public string GRNumber { get; set; }
        public string PlaceOfSupply { get; set; }
        public string E_WayBillNo { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Remarks { get; set; }
        public string ForwardToPIC { get; set; }
        public string Status { get; set; }
        public string PICApprovalStatus { get; set; }
        public string PICRemarks { get; set; }
        public string ForwardToStore { get; set; }
        public string StoreRemarks { get; set; }
        public string StoreApprovalStatus { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> PICApprovalDate { get; set; }
        public Nullable<System.DateTime> StoreApprovalDate { get; set; }
        public string TransferOutStatus { get; set; }
        public Nullable<System.DateTime> ReachingDateofDestination { get; set; }
        public string Session_Year { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<System.DateTime> E_WayBill_Date { get; set; }
        public Nullable<int> Is_Reject { get; set; }
        public string Reject_Remark { get; set; }
        public Nullable<System.DateTime> Reject_Date { get; set; }
    }
}
