//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIndentRequisition
    {
        public int Id { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string IndentNo { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string ItemGroupID { get; set; }
        public string ItemGroupName { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string UnitID { get; set; }
        public string Make { get; set; }
        public string PartNo { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> BalanceQuantity { get; set; }
        public Nullable<decimal> IssueQuantity { get; set; }
        public string SessionId { get; set; }
        public string SiteId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> AutoUniID { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public string IsRead { get; set; }
        public Nullable<int> BlockId { get; set; }
        public string BlockName { get; set; }
        public Nullable<int> FloorId { get; set; }
        public string FloorName { get; set; }
        public string IndentType { get; set; }
        public string IndentOtherDesc { get; set; }
        public string IndentSent { get; set; }
        public Nullable<decimal> Approved_Quantity { get; set; }
        public string Apporoved_By { get; set; }
        public string Apporoved_Status { get; set; }
        public Nullable<decimal> OrderBalance { get; set; }
        public Nullable<decimal> BalanceApprovedQty_After_Issue_Qty { get; set; }
        public Nullable<System.DateTime> IndentDate { get; set; }
        public Nullable<int> DivisionId { get; set; }
    }
}
