//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMMSPCDebitNote
    {
        public int TransId { get; set; }
        public string DebitNote_Code { get; set; }
        public string ProjectId { get; set; }
        public string Issue_Req_No { get; set; }
        public Nullable<System.DateTime> Issue_Req_Date { get; set; }
        public string PC_Code { get; set; }
        public Nullable<int> IssueTypeId { get; set; }
        public string ItemId { get; set; }
        public string Details_of_Billing_Department { get; set; }
        public Nullable<System.DateTime> DebitNote_Date { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Contractor_Type { get; set; }
        public string Session_Year { get; set; }
        public Nullable<int> DivisionId { get; set; }
    }
}
