//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMMSEquipmentMaster
    {
        public int TransId { get; set; }
        public string ItemGroupId { get; set; }
        public string ItemId { get; set; }
        public string EquipmentName { get; set; }
        public string OwnerName { get; set; }
        public string EquipmentRegNo { get; set; }
        public string ProjectId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string ManufactureName { get; set; }
        public string BodyColor { get; set; }
        public string BrandName { get; set; }
        public string Model { get; set; }
        public string EquipmentStatus { get; set; }
        public string FuelType { get; set; }
        public string EquipmentCondition { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
