//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMMSGSTTaxType
    {
        public int TransId { get; set; }
        public string TaxType { get; set; }
        public string TaxSlabCode { get; set; }
        public string TaxSlab { get; set; }
        public Nullable<decimal> TaxSlabPercentage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Description { get; set; }
    }
}
