//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMMSGateEntryFileDirectory
    {
        public int GDoc_ID { get; set; }
        public Nullable<decimal> GateEntryChild_Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> FileStatus { get; set; }
        public string UploadedBy { get; set; }
        public string ProjectId { get; set; }
    }
}
