//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMMSInsuranceMaster
    {
        public int TransId { get; set; }
        public string InsuranceCode { get; set; }
        public string InsuranceType { get; set; }
        public Nullable<decimal> InsuranceValue { get; set; }
        public Nullable<bool> IsInsurance { get; set; }
        public string InsuranceDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string InsuranceTextValue { get; set; }
    }
}
