//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPcContractorMaster
    {
        public int TransID { get; set; }
        public string CompanyID { get; set; }
        public string PRJID { get; set; }
        public string PcContractorID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string VendorType { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string VendorTypeCode { get; set; }
        public string PanNo { get; set; }
        public string TinNo { get; set; }
        public string EccNo { get; set; }
        public string Vat { get; set; }
        public string RegistrationType { get; set; }
        public string PinCode { get; set; }
        public string SalesTaxNo { get; set; }
        public string CSTNo { get; set; }
        public string ServiceTaxNo { get; set; }
        public string PhoneNo { get; set; }
        public string BlackListStatus { get; set; }
        public string ContactPerson { get; set; }
        public string MulRegistrationType { get; set; }
        public string PFNo { get; set; }
        public string ESINo { get; set; }
        public string AadharNo { get; set; }
        public string ContactNo { get; set; }
        public Nullable<decimal> ServiceTaxValue { get; set; }
        public string WorkTypeCode { get; set; }
        public Nullable<int> VMID { get; set; }
    
        public virtual tblPC_RegistrationType tblPC_RegistrationType { get; set; }
    }
}
