//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectParticularsDetailA
    {
        public int TransID { get; set; }
        public string CompanyID { get; set; }
        public string PRJID { get; set; }
        public string NameOfProject { get; set; }
        public string ProjectClause { get; set; }
        public string ProjectAmendments { get; set; }
        public string Location { get; set; }
        public string LocationClause { get; set; }
        public string LocationAmendments { get; set; }
        public Nullable<System.DateTime> DateOfAward { get; set; }
        public string AwardClause { get; set; }
        public string AwardAmendments { get; set; }
        public string LOINo { get; set; }
        public string LOINoClause { get; set; }
        public string LOINoAmendments { get; set; }
        public Nullable<System.DateTime> LOIDate { get; set; }
        public string LOIDateClause { get; set; }
        public string LOIDateAmendments { get; set; }
        public string NameOfRegion { get; set; }
        public string RegionClause { get; set; }
        public string RegionAmendments { get; set; }
        public string ProjectInchargeName { get; set; }
        public string ProjectInchargeMobileNo { get; set; }
        public string InchargeClause { get; set; }
        public string InchargeAmendments { get; set; }
        public string ClientName { get; set; }
        public string ClientAddress { get; set; }
        public string ClientMobileNo { get; set; }
        public string ClientClause { get; set; }
        public string ClientAmendments { get; set; }
        public string ProjectManagerName { get; set; }
        public string ProjectManagerAddress { get; set; }
        public string ProjectManagerMobileNo { get; set; }
        public string ProjectManagerClause { get; set; }
        public string ProjectManagerAmendments { get; set; }
        public string ArchitectName { get; set; }
        public string ArchitectAddress { get; set; }
        public string ArchitectMobileNo { get; set; }
        public string ArchitectClause { get; set; }
        public string ArchitectAmendments { get; set; }
        public string StructuralConsultantName { get; set; }
        public string StructuralConsultantAddress { get; set; }
        public string StructuralConsultantMobileNo { get; set; }
        public string StructuralClause { get; set; }
        public string StructuralAmendments { get; set; }
        public string MechanicalName { get; set; }
        public string MechanicalAddress { get; set; }
        public string MechanicalMobileNo { get; set; }
        public string MechanicalClause { get; set; }
        public string MechanicalAmendments { get; set; }
        public string ElectricalName { get; set; }
        public string ElectricalAddress { get; set; }
        public string ElectricalMobileNo { get; set; }
        public string ElectricalClause { get; set; }
        public string ElectricalAmendments { get; set; }
        public string PlumbingName { get; set; }
        public string PlumbingAddress { get; set; }
        public string PlumbingMobileNo { get; set; }
        public string PlumbingClause { get; set; }
        public string PlumbingAmendments { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ClientCountry { get; set; }
        public string ClientState { get; set; }
        public string ClientCity { get; set; }
        public string ProjectManagerCountry { get; set; }
        public string ProjectManagerState { get; set; }
        public string ProjectManagerCity { get; set; }
        public string ArchitectCountry { get; set; }
        public string ArchitectState { get; set; }
        public string ArchitectCity { get; set; }
        public string StructuralCountry { get; set; }
        public string StructuralState { get; set; }
        public string StructuralCity { get; set; }
        public string MechanicalCountry { get; set; }
        public string MechanicalState { get; set; }
        public string MechanicalCity { get; set; }
        public string ElectricalCountry { get; set; }
        public string ElectricalState { get; set; }
        public string ElectricalCity { get; set; }
        public string PlumbingCountry { get; set; }
        public string PlumbingState { get; set; }
        public string PlumbingCity { get; set; }
        public Nullable<System.DateTime> StipulatedDateOfStart { get; set; }
        public Nullable<System.DateTime> ActualDateOfStart { get; set; }
        public Nullable<System.DateTime> StipulatedDateOfFinish { get; set; }
        public string StipulatedDateStartClause { get; set; }
        public string StipulatedDateStartAmendments { get; set; }
        public string ActualDateStartClause { get; set; }
        public string ActualDateStartAmendments { get; set; }
        public string StipulatedDateFinishClause { get; set; }
        public string StipulatedDateFinishAmendments { get; set; }
        public string ClientZipCode { get; set; }
        public string ProjectManagerZipCode { get; set; }
        public string ArchitectZipCode { get; set; }
        public string StructuralZipCode { get; set; }
        public string MechanicalZipCode { get; set; }
        public string ElectricalZipCode { get; set; }
        public string PlumbingZipCode { get; set; }
        public string ClientPhoneNo { get; set; }
        public string ProjectManagerPhoneNo { get; set; }
        public string ArchitectPhoneNo { get; set; }
        public string StructuralPhoneNo { get; set; }
        public string MechanicalPhoneNo { get; set; }
        public string ElectricalPhoneNo { get; set; }
        public string PlumbingPhoneNo { get; set; }
        public Nullable<decimal> OriginalContractValue { get; set; }
        public string OCVWord { get; set; }
        public string OCVClause { get; set; }
        public string OCVAmendments { get; set; }
        public Nullable<decimal> RevisedContractValue { get; set; }
        public string RCVWord { get; set; }
        public string RCVClause { get; set; }
        public string RCVAmendments { get; set; }
        public Nullable<decimal> ExpectedContractValue { get; set; }
        public string ECVWord { get; set; }
        public string ECVClause { get; set; }
        public string ECVAmendments { get; set; }
        public string ClientEmail { get; set; }
        public string ClientFax { get; set; }
        public string ProjectManagerEmail { get; set; }
        public string ProjectManagerFax { get; set; }
        public string ArchitectEmail { get; set; }
        public string ArchitectFax { get; set; }
        public string StructuralEmail { get; set; }
        public string StructuralFax { get; set; }
        public string MechanicalEmail { get; set; }
        public string MechanicalFax { get; set; }
        public string ElectricalEmail { get; set; }
        public string ElectricalFax { get; set; }
        public string PlumbingEmail { get; set; }
        public string PlumbingFax { get; set; }
    }
}
