//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseLimitValueByProjectWise
    {
        public int TransId { get; set; }
        public Nullable<int> EmengencyPurchaseType { get; set; }
        public string ProjectId { get; set; }
        public Nullable<int> EmengencyLimitValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> NormalPurchaseType { get; set; }
        public Nullable<int> NormalLimitValue { get; set; }
    }
}
