//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectGSTNo
    {
        public int TransID { get; set; }
        public string ProjectId { get; set; }
        public string StateId { get; set; }
        public string GSTNo { get; set; }
    }
}
