//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReturnQtyChild
    {
        public int Id { get; set; }
        public Nullable<int> MId { get; set; }
        public Nullable<int> Issue_UId { get; set; }
        public string ReturnNo { get; set; }
        public string IndentNo { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
