//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUnitConversionMaster
    {
        public int TransId { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public Nullable<decimal> UnitRate { get; set; }
        public string UnitConversionCode { get; set; }
        public string UnitConversionName { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
