//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUploadedBill
    {
        public int Id { get; set; }
        public string Filename { get; set; }
        public string FileName1 { get; set; }
        public string Extension { get; set; }
        public string FileType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<bool> status { get; set; }
        public string MRN { get; set; }
        public string Remarks { get; set; }
    }
}
