//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUniteConversionMapped
    {
        public int TransId { get; set; }
        public string ProjectId { get; set; }
        public string SourceLocationId { get; set; }
        public string ItemGroupId { get; set; }
        public string ItemId { get; set; }
        public string UnitFromId { get; set; }
        public string UnitConversionId { get; set; }
        public Nullable<decimal> UnitConversationRate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public string CompanyId { get; set; }
        public Nullable<bool> IsMapped { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
