//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorDebitNoteMaster
    {
        public decimal UId { get; set; }
        public string ProjectNumber { get; set; }
        public string SupplierNo { get; set; }
        public string PurchaseOrderNo { get; set; }
        public string VendorDebitNo { get; set; }
        public Nullable<System.DateTime> VendorDebitDate { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> SubTotal1 { get; set; }
        public Nullable<decimal> SubTotal2 { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> Total_Cartage { get; set; }
        public Nullable<decimal> Total_Insurance { get; set; }
        public Nullable<decimal> Total_Taxable { get; set; }
        public Nullable<decimal> Total_CGST { get; set; }
        public Nullable<decimal> Total_SGSTAndUTGST { get; set; }
        public Nullable<decimal> Total_IGST { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string GRNNo { get; set; }
        public string Send_To { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsAllItemDebited { get; set; }
        public Nullable<System.DateTime> LastUpdateDebitedDate { get; set; }
        public string Reason { get; set; }
        public Nullable<int> DivisionId { get; set; }
    }
}
