//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblVendorMaster()
        {
            this.TbCashPurchaseMasters = new HashSet<TbCashPurchaseMaster>();
        }
    
        public int TransID { get; set; }
        public string CompanyID { get; set; }
        public string PRJID { get; set; }
        public string VendorID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string VendorType { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string VendorTypeCode { get; set; }
        public string PanNo { get; set; }
        public string TinNo { get; set; }
        public string EccNo { get; set; }
        public string Vat { get; set; }
        public string RegistrationType { get; set; }
        public string PinCode { get; set; }
        public string SalesTaxNo { get; set; }
        public string CSTNo { get; set; }
        public string ServiceTaxNo { get; set; }
        public string PhoneNo { get; set; }
        public string BlackListStatus { get; set; }
        public string ContactPerson { get; set; }
        public string MulRegistrationType { get; set; }
        public string VAT_No { get; set; }
        public string GST_NO { get; set; }
        public string Aadhaar_No { get; set; }
        public Nullable<int> From_API { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbCashPurchaseMaster> TbCashPurchaseMasters { get; set; }
        public virtual tblRegistrationType tblRegistrationType { get; set; }
    }
}
